- hosts: preprod[1]
  user: root
  become: yes
  connection: ssh
  gather_facts: yes

  vars:
    package: httpd

  tasks:
    - name: remove httpd
      yum:
        name: httpd
        state: absent
        autoremove: yes
      when: package == "httpd"

    - name: install the latest version of httpd
      yum:
        name: httpd
        state: latest
      when: ansible_facts['os_family'] == "RedHat"
