- hosts: preprod[0]
  user: root
  become: yes
  connection: ssh
  gather_facts: yes

  tasks:
    - name: install git on preprod 1st server
      yum:
        name: git
        state: latest


- hosts: dev[1]
  user: root
  connection: ssh
  become: yes
  gather_facts: yes

  tasks:
    - name: download maven
      get_url:
        url: https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.zip
        dest: /mnt
        mode: 0700

