- hosts: dev[1]
  user: root
  become: yes
  connection: ssh
  gather_facts: yes

  vars:
    package_name: httpd
    src_path: /root/index.html
    dest_path: /var/www/html

  tasks:
    - name: make sure service is stopped
      systemd:
        state: stopped
        name: "{{ package_name }}"

    - name: remove httpd server
      yum:
        name: "{{ package_name }}"
        state: removed
    - name: delete index file
      shell: rm -rf /root/index.html

    - name: delete html dir
      shell: rm -rf /var/www/html 
        

  
