---
# handlers file for httpd
#

- name: httpd service is running
  systemd:
    name: "{{ package_name }}"
    enabled: yes

- name: copy file
  copy:
    src: "{{ src_path }}"
    dest: "{{ dest_path }}"
    remote_src: yes
